### ISSUE TITLE
Logo and Possible names

### ISSUE THREAD

**Issue by raghunayyar** [raghunayyar/devanagari-dictionary#4]
@sitarashah @girish-dalvi @dil33pm : we can discuss this here now.

**Comment by raghunayyar** [comment]
As far as I remember, @girish-dalvi suggested : Devanagari Glyph Dictionary as a default if nothing works out and in a discussion with @sitarashah we came out with 'Glyph Diaries'. What do you think? We need the logo asap. :)

**Comment by raghunayyar** [comment]
@dil33pm inputs are welcome.

**Comment by sitarashah** [comment]
@raghunayyar  I told you Girish is fine with the name. I am making a few logos and showing him on Tuesday

**Comment by raghunayyar** [comment]
Great, today is Wednesday, can I have a look at them? @sitarashah
